CREATE DATABASE EDUTEST7 AUTOMATIC STORAGE YES ON 'D:\' USING CODESET UTF-8 TERRITORY RO;
CONNECT TO EDUTEST7;

CREATE TABLE SILVIU.MARKET_RULE (
 ID_MARKET_RULE BIGINT  NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ) , 
 COUNTRY_NUMBER VARCHAR (10)  NOT NULL , 
 BRANCH INTEGER  NOT NULL , 
 STOCK_CATEGORY VARCHAR (10)  NOT NULL ,   
 IS_ACTIVE SMALLINT  NOT NULL  , 
 CONSTRAINT UNIQUE_KEY_COUNTRYNUMBER_BRANCH_STOCKCATEGORY UNIQUE ( COUNTRY_NUMBER, BRANCH, STOCK_CATEGORY),
 CONSTRAINT PRIMARY_KEY PRIMARY KEY ( ID_MARKET_RULE  )  
) ; 

CREATE TABLE SILVIU.VEHICLE(
 ID_VEHICLE  BIGINT  NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) , 
 COUNTRY_NUMBER VARCHAR (10)  NOT NULL , 
 BRANCH INTEGER  NOT NULL , 
 STOCK_CATEGORY VARCHAR (10)  NOT NULL ,   
 MODEL VARCHAR (30)  ,   
 CLASSE VARCHAR (30)  , 
 CHASSIS_SERIAL VARCHAR (30)   NOT NULL ,
 ENGINE_CODE VARCHAR (30)  , 
 ENGINE_FUEL_TYPE VARCHAR (30)  , 
 CONSTRAINT UNIQUE_KEY_CHASSISSERIAL UNIQUE ( CHASSIS_SERIAL),
 CONSTRAINT PRIMARY_KEY PRIMARY KEY ( ID_VEHICLE  ) 
);

CREATE TABLE SILVIU.EVALUATION_RULE(
 ID_EVALUATION_RULE BIGINT  NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) , 
 VEHICLE_ATTRIBUTE VARCHAR (50)  , 
 VEHICLE_ATTRIBUTE_SOURCE VARCHAR (50) , 
 VEHICLE_ATTRIBUTE_TARGET VARCHAR (50)  , 
 MARKET_RULE_ID BIGINT ,  
 CONSTRAINT PRIMARY_KEY PRIMARY KEY ( ID_EVALUATION_RULE ) 
 ) ;

CREATE TABLE SILVIU.RULE_CONDITION(
 ID_RULE_CONDITION BIGINT  NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) , 
 VEHICLE_ATTRIBUTE_NAME VARCHAR (50)  NOT NULL , 
 VEHICLE_ATTRIBUTE_VALUE VARCHAR (50) NOT NULL , 
 ID_EVALUATION_RULE_IND BIGINT,  
 CONSTRAINT PRIMARY_KEY PRIMARY KEY (ID_RULE_CONDITION ) ,
 CONSTRAINT FK_RULE FOREIGN KEY (ID_EVALUATION_RULE_IND ) REFERENCES SILVIU.EVALUATION_RULE (ID_EVALUATION_RULE) 
 ) ;

CREATE TABLE SILVIU.RULE_ACTIVITY(
 ID_RULE_ACTIVITY BIGINT  NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) , 
 VEHICLE_ATTRIBUTE_NAME VARCHAR (50)  NOT NULL , 
 VEHICLE_ATTRIBUTE_VALUE VARCHAR (50) NOT NULL , 
 ID_EVALUATION_RULE_IND BIGINT,  
 CONSTRAINT PRIMARY_KEY PRIMARY KEY (ID_RULE_ACTIVITY) ,
 CONSTRAINT FK_RULE FOREIGN KEY (ID_EVALUATION_RULE_IND ) REFERENCES SILVIU.EVALUATION_RULE (ID_EVALUATION_RULE ) 
 ) ;

CREATE TABLE SILVIU.EVALUATION_RESULT(
  ID_EVALUATION_RESULT BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  DATE_OF_EVALUATION TIMESTAMP,
  ID_VEHICLE_IND BIGINT,
  EVALUATION_RULES_APPLIED VARCHAR (255),
  CONSTRAINT PRIMARY_KEY PRIMARY KEY (ID_EVALUATION_RESULT) ,
 CONSTRAINT FK_VEHICLE FOREIGN KEY (ID_VEHICLE_IND  ) REFERENCES SILVIU.VEHICLE (ID_VEHICLE) 
);

CREATE TABLE SILVIU.EVALUATION_RESULT_RULE_DETAIL(
  ID_EVALUATION_RESULT_RULE_DETAIL BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  RULE_STATUS VARCHAR(10),
  MESSAGE CLOB(1M),
  ID_EVALUATION_RESULT_IND BIGINT,
  ID_EVALUATION_RULE_IND BIGINT,
  CONSTRAINT PRIMARY_KEY PRIMARY KEY (ID_EVALUATION_RESULT_RULE_DETAIL ) ,
 CONSTRAINT FK_RULE FOREIGN KEY (ID_EVALUATION_RULE_IND ) REFERENCES SILVIU.EVALUATION_RULE (ID_EVALUATION_RULE) ,
 CONSTRAINT FK_EVALUATION_RESULT FOREIGN KEY (ID_EVALUATION_RESULT_IND ) REFERENCES SILVIU.EVALUATION_RESULT (ID_EVALUATION_RESULT) 
);

CREATE TABLE SILVIU.STOCK_CATEGORY (
 ID_STOCK_CATEGORY BIGINT  NOT NULL  GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1 ) , 
 NAME VARCHAR (20)  NOT NULL , 
 DESCRIPTION VARCHAR(255), 
 CONSTRAINT PRIMARY_KEY PRIMARY KEY ( ID_STOCK_CATEGORY)  
) ;

